PWD=/Volumes/USB20FD/packet-manipulation-library
PACKETDIR=/Volumes/USB20FD/packet-manipulation-library/Packet
INETDIR=/Volumes/USB20FD/packet-manipulation-library/Packet/Inet
LINKDIR=/Volumes/USB20FD/packet-manipulation-library/Packet/Link
TRANSDIR=/Volumes/USB20FD/packet-manipulation-library/Packet/Trans
APPDIR=/Volumes/USB20FD/packet-manipulation-library/Packet/App
APPSOURCE=/Volumes/USB20FD/packet-manipulation-library/Packet/App/app.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/App/raw.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/App/dnsPacket.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/App/staticBuffer.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/App/dnsRecord.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/App/dnsQuestion.cpp
TRANSSOURCE=/Volumes/USB20FD/packet-manipulation-library/Packet/Trans/tcp.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/udp.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/tcpOptions.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/trans.cpp
INETSOURCE=/Volumes/USB20FD/packet-manipulation-library/Packet/Inet/inet.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/Inet/ipv4.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/Inet/icmp.cpp
LINKSOURCE=/Volumes/USB20FD/packet-manipulation-library/Packet/Link/link.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/Link/ethernet.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/Link/mac.cpp
PACKETSOURCE=/Volumes/USB20FD/packet-manipulation-library/Packet/packetBuilder.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/packet.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/packetBuffer.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/App/app.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/App/raw.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/App/dnsPacket.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/App/staticBuffer.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/App/dnsRecord.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/App/dnsQuestion.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/tcp.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/udp.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/tcpOptions.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/trans.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/Inet/inet.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/Inet/ipv4.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/Inet/icmp.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/Link/link.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/Link/ethernet.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/Link/mac.cpp
APPOBJS=$(APPSOURCE:%.cpp=%.o)
TRANSOBJS=$(TRANSSOURCE:%.cpp=%.o)
INETOBJS=$(INETSOURCE:%.cpp=%.o)
LINKOBJS=$(LINKSOURCE:%.cpp=%.o)
PACKETOBJS=$(PACKETSOURCE:%.cpp=%.o)
APPHEADERS=/Volumes/USB20FD/packet-manipulation-library/Packet/App/appData.h /Volumes/USB20FD/packet-manipulation-library/Packet/App/app.h /Volumes/USB20FD/packet-manipulation-library/Packet/App/raw.h /Volumes/USB20FD/packet-manipulation-library/Packet/App/dnsPacket.h /Volumes/USB20FD/packet-manipulation-library/Packet/App/staticBuffer.h /Volumes/USB20FD/packet-manipulation-library/Packet/App/dnsRecord.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/App/dnsQuestion.cpp
TRANSHEADERS=/Volumes/USB20FD/packet-manipulation-library/Packet/Trans/tcp.h /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/udp.h /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/tcpOptions.h /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/trans.h /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/transData.h /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/eolOption.h /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/mssOption.h /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/noopOption.h /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/sackOption.h /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/sackPermittedOption.h /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/timeStampOption.h /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/wsOption.h
INETHEADERS=/Volumes/USB20FD/packet-manipulation-library/Packet/Inet/inetData.h /Volumes/USB20FD/packet-manipulation-library/Packet/Inet/inet.h /Volumes/USB20FD/packet-manipulation-library/Packet/Inet/ipv4.h /Volumes/USB20FD/packet-manipulation-library/Packet/Inet/icmp.h
LINKHEADERS=/Volumes/USB20FD/packet-manipulation-library/Packet/Link/linkData.h /Volumes/USB20FD/packet-manipulation-library/Packet/Link/link.h /Volumes/USB20FD/packet-manipulation-library/Packet/Link/ethernet.h /Volumes/USB20FD/packet-manipulation-library/Packet/Link/mac.h
PACKETHEADERS=/Volumes/USB20FD/packet-manipulation-library/Packet/packetBuilder.h /Volumes/USB20FD/packet-manipulation-library/Packet/packet.h /Volumes/USB20FD/packet-manipulation-library/Packet/packetBuffer.h /Volumes/USB20FD/packet-manipulation-library/Packet/App/appData.h /Volumes/USB20FD/packet-manipulation-library/Packet/App/app.h /Volumes/USB20FD/packet-manipulation-library/Packet/App/raw.h /Volumes/USB20FD/packet-manipulation-library/Packet/App/dnsPacket.h /Volumes/USB20FD/packet-manipulation-library/Packet/App/staticBuffer.h /Volumes/USB20FD/packet-manipulation-library/Packet/App/dnsRecord.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/App/dnsQuestion.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/tcp.h /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/udp.h /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/tcpOptions.h /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/trans.h /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/transData.h /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/eolOption.h /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/mssOption.h /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/noopOption.h /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/sackOption.h /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/sackPermittedOption.h /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/timeStampOption.h /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/wsOption.h /Volumes/USB20FD/packet-manipulation-library/Packet/Inet/inetData.h /Volumes/USB20FD/packet-manipulation-library/Packet/Inet/inet.h /Volumes/USB20FD/packet-manipulation-library/Packet/Inet/ipv4.h /Volumes/USB20FD/packet-manipulation-library/Packet/Inet/icmp.h /Volumes/USB20FD/packet-manipulation-library/Packet/Link/linkData.h /Volumes/USB20FD/packet-manipulation-library/Packet/Link/link.h /Volumes/USB20FD/packet-manipulation-library/Packet/Link/ethernet.h /Volumes/USB20FD/packet-manipulation-library/Packet/Link/mac.h
PACKETTESTDIR=/Volumes/USB20FD/packet-manipulation-library/Packet/TestCode
INETTESTDIR=/Volumes/USB20FD/packet-manipulation-library/Packet/Inet/TestCode
LINKTESTDIR=/Volumes/USB20FD/packet-manipulation-library/Packet/Link/TestCode
TRANSTESTDIR=/Volumes/USB20FD/packet-manipulation-library/Packet/Trans/TestCode
APPTESTDIR=/Volumes/USB20FD/packet-manipulation-library/Packet/App/TestCode
PACKETTESTSOURCE=
APPTESTSOURCE=/Volumes/USB20FD/packet-manipulation-library/Packet/App/TestCode/testRaw.cpp
TRANSTESTSOURCE=/Volumes/USB20FD/packet-manipulation-library/Packet/Trans/TestCode/testTcp.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/Trans/TestCode/testUdp.cpp
INETTESTSOURCE=/Volumes/USB20FD/packet-manipulation-library/Packet/Inet/TestCode/testIcmp.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/Inet/TestCode/testIPv4.cpp
LINKTESTSOURCE=/Volumes/USB20FD/packet-manipulation-library/Packet/Link/TestCode/ethernetTest.cpp /Volumes/USB20FD/packet-manipulation-library/Packet/Link/TestCode/macTest.cpp
PACKETTESTOBJS=$(PACKETTESTSOURCE:%.cpp=%.o)
APPTESTOBJS=$(APPTESTSOURCE:%.cpp=%.o)
TRANSTESTOBJS=$(TRANSTESTSOURCE:%.cpp=%.o)
INETTESTOBJS=$(INETTESTSOURCE:%.cpp=%.o)
LINKTESTOBJS=$(LINKTESTSOURCE:%.cpp=%.o)
