PWD=/home/scap/googleCode/packet-manipulation-library
PACKETDIR=/home/scap/googleCode/packet-manipulation-library/Packet
INETDIR=/home/scap/googleCode/packet-manipulation-library/Packet/Inet
LINKDIR=/home/scap/googleCode/packet-manipulation-library/Packet/Link
TRANSDIR=/home/scap/googleCode/packet-manipulation-library/Packet/Trans
APPDIR=/home/scap/googleCode/packet-manipulation-library/Packet/App
APPSOURCE=/home/scap/googleCode/packet-manipulation-library/Packet/App/app.cpp /home/scap/googleCode/packet-manipulation-library/Packet/App/raw.cpp /home/scap/googleCode/packet-manipulation-library/Packet/App/dnsPacket.cpp /home/scap/googleCode/packet-manipulation-library/Packet/App/staticBuffer.cpp /home/scap/googleCode/packet-manipulation-library/Packet/App/dnsRecord.cpp /home/scap/googleCode/packet-manipulation-library/Packet/App/dnsQuestion.cpp
TRANSSOURCE=/home/scap/googleCode/packet-manipulation-library/Packet/Trans/tcp.cpp /home/scap/googleCode/packet-manipulation-library/Packet/Trans/udp.cpp /home/scap/googleCode/packet-manipulation-library/Packet/Trans/tcpOptions.cpp /home/scap/googleCode/packet-manipulation-library/Packet/Trans/trans.cpp
INETSOURCE=/home/scap/googleCode/packet-manipulation-library/Packet/Inet/inet.cpp /home/scap/googleCode/packet-manipulation-library/Packet/Inet/ipv4.cpp /home/scap/googleCode/packet-manipulation-library/Packet/Inet/icmp.cpp
LINKSOURCE=/home/scap/googleCode/packet-manipulation-library/Packet/Link/link.cpp /home/scap/googleCode/packet-manipulation-library/Packet/Link/ethernet.cpp /home/scap/googleCode/packet-manipulation-library/Packet/Link/mac.cpp
PACKETSOURCE=/home/scap/googleCode/packet-manipulation-library/Packet/packetBuilder.cpp /home/scap/googleCode/packet-manipulation-library/Packet/packet.cpp /home/scap/googleCode/packet-manipulation-library/Packet/packetBuffer.cpp /home/scap/googleCode/packet-manipulation-library/Packet/App/app.cpp /home/scap/googleCode/packet-manipulation-library/Packet/App/raw.cpp /home/scap/googleCode/packet-manipulation-library/Packet/App/dnsPacket.cpp /home/scap/googleCode/packet-manipulation-library/Packet/App/staticBuffer.cpp /home/scap/googleCode/packet-manipulation-library/Packet/App/dnsRecord.cpp /home/scap/googleCode/packet-manipulation-library/Packet/App/dnsQuestion.cpp /home/scap/googleCode/packet-manipulation-library/Packet/Trans/tcp.cpp /home/scap/googleCode/packet-manipulation-library/Packet/Trans/udp.cpp /home/scap/googleCode/packet-manipulation-library/Packet/Trans/tcpOptions.cpp /home/scap/googleCode/packet-manipulation-library/Packet/Trans/trans.cpp /home/scap/googleCode/packet-manipulation-library/Packet/Inet/inet.cpp /home/scap/googleCode/packet-manipulation-library/Packet/Inet/ipv4.cpp /home/scap/googleCode/packet-manipulation-library/Packet/Inet/icmp.cpp /home/scap/googleCode/packet-manipulation-library/Packet/Link/link.cpp /home/scap/googleCode/packet-manipulation-library/Packet/Link/ethernet.cpp /home/scap/googleCode/packet-manipulation-library/Packet/Link/mac.cpp
APPOBJS=$(APPSOURCE:%.cpp=%.o)
TRANSOBJS=$(TRANSSOURCE:%.cpp=%.o)
INETOBJS=$(INETSOURCE:%.cpp=%.o)
LINKOBJS=$(LINKSOURCE:%.cpp=%.o)
PACKETOBJS=$(PACKETSOURCE:%.cpp=%.o)
APPHEADERS=/home/scap/googleCode/packet-manipulation-library/Packet/App/appData.h /home/scap/googleCode/packet-manipulation-library/Packet/App/app.h /home/scap/googleCode/packet-manipulation-library/Packet/App/raw.h /home/scap/googleCode/packet-manipulation-library/Packet/App/dnsPacket.h /home/scap/googleCode/packet-manipulation-library/Packet/App/staticBuffer.h /home/scap/googleCode/packet-manipulation-library/Packet/App/dnsRecord.cpp /home/scap/googleCode/packet-manipulation-library/Packet/App/dnsQuestion.cpp
TRANSHEADERS=/home/scap/googleCode/packet-manipulation-library/Packet/Trans/tcp.h /home/scap/googleCode/packet-manipulation-library/Packet/Trans/udp.h /home/scap/googleCode/packet-manipulation-library/Packet/Trans/tcpOptions.h /home/scap/googleCode/packet-manipulation-library/Packet/Trans/trans.h /home/scap/googleCode/packet-manipulation-library/Packet/Trans/transData.h /home/scap/googleCode/packet-manipulation-library/Packet/Trans/eolOption.h /home/scap/googleCode/packet-manipulation-library/Packet/Trans/mssOption.h /home/scap/googleCode/packet-manipulation-library/Packet/Trans/noopOption.h /home/scap/googleCode/packet-manipulation-library/Packet/Trans/sackOption.h /home/scap/googleCode/packet-manipulation-library/Packet/Trans/sackPermittedOption.h /home/scap/googleCode/packet-manipulation-library/Packet/Trans/timeStampOption.h /home/scap/googleCode/packet-manipulation-library/Packet/Trans/wsOption.h
INETHEADERS=/home/scap/googleCode/packet-manipulation-library/Packet/Inet/inetData.h /home/scap/googleCode/packet-manipulation-library/Packet/Inet/inet.h /home/scap/googleCode/packet-manipulation-library/Packet/Inet/ipv4.h /home/scap/googleCode/packet-manipulation-library/Packet/Inet/icmp.h
LINKHEADERS=/home/scap/googleCode/packet-manipulation-library/Packet/Link/linkData.h /home/scap/googleCode/packet-manipulation-library/Packet/Link/link.h /home/scap/googleCode/packet-manipulation-library/Packet/Link/ethernet.h /home/scap/googleCode/packet-manipulation-library/Packet/Link/mac.h
PACKETHEADERS=/home/scap/googleCode/packet-manipulation-library/Packet/packetBuilder.h /home/scap/googleCode/packet-manipulation-library/Packet/packet.h /home/scap/googleCode/packet-manipulation-library/Packet/packetBuffer.h /home/scap/googleCode/packet-manipulation-library/Packet/App/appData.h /home/scap/googleCode/packet-manipulation-library/Packet/App/app.h /home/scap/googleCode/packet-manipulation-library/Packet/App/raw.h /home/scap/googleCode/packet-manipulation-library/Packet/App/dnsPacket.h /home/scap/googleCode/packet-manipulation-library/Packet/App/staticBuffer.h /home/scap/googleCode/packet-manipulation-library/Packet/App/dnsRecord.cpp /home/scap/googleCode/packet-manipulation-library/Packet/App/dnsQuestion.cpp /home/scap/googleCode/packet-manipulation-library/Packet/Trans/tcp.h /home/scap/googleCode/packet-manipulation-library/Packet/Trans/udp.h /home/scap/googleCode/packet-manipulation-library/Packet/Trans/tcpOptions.h /home/scap/googleCode/packet-manipulation-library/Packet/Trans/trans.h /home/scap/googleCode/packet-manipulation-library/Packet/Trans/transData.h /home/scap/googleCode/packet-manipulation-library/Packet/Trans/eolOption.h /home/scap/googleCode/packet-manipulation-library/Packet/Trans/mssOption.h /home/scap/googleCode/packet-manipulation-library/Packet/Trans/noopOption.h /home/scap/googleCode/packet-manipulation-library/Packet/Trans/sackOption.h /home/scap/googleCode/packet-manipulation-library/Packet/Trans/sackPermittedOption.h /home/scap/googleCode/packet-manipulation-library/Packet/Trans/timeStampOption.h /home/scap/googleCode/packet-manipulation-library/Packet/Trans/wsOption.h /home/scap/googleCode/packet-manipulation-library/Packet/Inet/inetData.h /home/scap/googleCode/packet-manipulation-library/Packet/Inet/inet.h /home/scap/googleCode/packet-manipulation-library/Packet/Inet/ipv4.h /home/scap/googleCode/packet-manipulation-library/Packet/Inet/icmp.h /home/scap/googleCode/packet-manipulation-library/Packet/Link/linkData.h /home/scap/googleCode/packet-manipulation-library/Packet/Link/link.h /home/scap/googleCode/packet-manipulation-library/Packet/Link/ethernet.h /home/scap/googleCode/packet-manipulation-library/Packet/Link/mac.h
PACKETTESTDIR=/home/scap/googleCode/packet-manipulation-library/Packet/TestCode
INETTESTDIR=/home/scap/googleCode/packet-manipulation-library/Packet/Inet/TestCode
LINKTESTDIR=/home/scap/googleCode/packet-manipulation-library/Packet/Link/TestCode
TRANSTESTDIR=/home/scap/googleCode/packet-manipulation-library/Packet/Trans/TestCode
APPTESTDIR=/home/scap/googleCode/packet-manipulation-library/Packet/App/TestCode
PACKETTESTSOURCE=
APPTESTSOURCE=/home/scap/googleCode/packet-manipulation-library/Packet/App/TestCode/testRaw.cpp
TRANSTESTSOURCE=/home/scap/googleCode/packet-manipulation-library/Packet/Trans/TestCode/testTcp.cpp /home/scap/googleCode/packet-manipulation-library/Packet/Trans/TestCode/testUdp.cpp
INETTESTSOURCE=/home/scap/googleCode/packet-manipulation-library/Packet/Inet/TestCode/testIcmp.cpp /home/scap/googleCode/packet-manipulation-library/Packet/Inet/TestCode/testIPv4.cpp
LINKTESTSOURCE=/home/scap/googleCode/packet-manipulation-library/Packet/Link/TestCode/ethernetTest.cpp /home/scap/googleCode/packet-manipulation-library/Packet/Link/TestCode/macTest.cpp
PACKETTESTOBJS=$(PACKETTESTSOURCE:%.cpp=%.o)
APPTESTOBJS=$(APPTESTSOURCE:%.cpp=%.o)
TRANSTESTOBJS=$(TRANSTESTSOURCE:%.cpp=%.o)
INETTESTOBJS=$(INETTESTSOURCE:%.cpp=%.o)
LINKTESTOBJS=$(LINKTESTSOURCE:%.cpp=%.o)
